# Generated by Django 4.2.7 on 2025-11-04 13:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Исходное имя файла')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('google_sheets', 'Google Sheets'), ('zip', 'ZIP Archive')], max_length=20, verbose_name='Тип файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('file_path', models.CharField(max_length=500, verbose_name='Путь к файлу')),
                ('google_sheet_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на Google Sheets')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('items', models.JSONField(default=list, verbose_name='Позиции заказа')),
                ('export_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel')], default='excel', max_length=10, verbose_name='Формат экспорта')),
                ('export_file_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Путь к экспортированному файлу')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParsedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brewery', models.CharField(blank=True, max_length=200, verbose_name='Пивоварня')),
                ('beer_name', models.CharField(blank=True, max_length=200, verbose_name='Название пива')),
                ('style', models.CharField(blank=True, max_length=100, verbose_name='Стиль пива')),
                ('abv', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Крепость (%)')),
                ('ibu', models.CharField(blank=True, max_length=50, verbose_name='Горечь (IBU)')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('currency', models.CharField(default='RUB', max_length=10, verbose_name='Валюта')),
                ('volume', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Объём (л)')),
                ('format_type', models.CharField(blank=True, max_length=50, verbose_name='Формат')),
                ('stock', models.CharField(blank=True, max_length=100, verbose_name='Остатки')),
                ('supplier_name', models.CharField(blank=True, max_length=200, verbose_name='Поставщик')),
                ('raw_source_location', models.JSONField(blank=True, default=dict, verbose_name='Источник данных')),
                ('is_selected', models.BooleanField(default=False, verbose_name='Выбрано для заказа')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='parser_app.file', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Распарсенная позиция',
                'verbose_name_plural': 'Распарсенные позиции',
                'ordering': ['file', 'brewery', 'beer_name'],
            },
        ),
        migrations.CreateModel(
            name='FileMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacts', models.JSONField(blank=True, default=dict, verbose_name='Контакты')),
                ('extra_text', models.JSONField(blank=True, default=list, verbose_name='Служебные тексты')),
                ('summary', models.JSONField(blank=True, default=dict, verbose_name='Статистика парсинга')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='parser_app.file', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Метаданные файла',
                'verbose_name_plural': 'Метаданные файлов',
            },
        ),
    ]
