# Generated by Django 4.2.7 on 2025-11-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseditem',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание пива'),
        ),
    ]
