# Generated by Django 4.2.7 on 2025-11-27 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_parseditem_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TapLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название локации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='Номер крана')),
                ('brewery', models.CharField(blank=True, max_length=255, verbose_name='Пивоварня')),
                ('beer_name', models.CharField(blank=True, max_length=255, verbose_name='Название пива')),
                ('price_per_liter', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена за литр')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taps', to='parser_app.taplocation', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Кран',
                'verbose_name_plural': 'Краны',
                'ordering': ['location', 'position'],
                'unique_together': {('location', 'position')},
            },
        ),
    ]
