# Generated by Django 4.2.7 on 2025-11-27 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0003_taplocation_tap'),
    ]

    operations = [
        migrations.AddField(
            model_name='tap',
            name='next_beer_1',
            field=models.CharField(blank=True, max_length=500, verbose_name='Следующее пиво 1'),
        ),
        migrations.AddField(
            model_name='tap',
            name='next_beer_2',
            field=models.CharField(blank=True, max_length=500, verbose_name='Следующее пиво 2'),
        ),
        migrations.AddField(
            model_name='tap',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('free', 'Свободно'), ('reserved', 'Зарезервирован')], default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='AvailableBeer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brewery', models.CharField(max_length=255, verbose_name='Пивоварня')),
                ('beer_name', models.CharField(max_length=255, verbose_name='Название пива')),
                ('price_per_liter', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена за литр')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_beers', to='parser_app.taplocation', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Доступное пиво',
                'verbose_name_plural': 'Доступное пиво',
                'ordering': ['brewery', 'beer_name'],
            },
        ),
    ]
