# Generated by Django 4.2.7 on 2025-11-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0004_tap_next_beer_1_tap_next_beer_2_tap_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tap',
            name='color_current',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Цвет текущего'),
        ),
        migrations.AddField(
            model_name='tap',
            name='color_next1',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Цвет след 1'),
        ),
        migrations.AddField(
            model_name='tap',
            name='color_next2',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Цвет след 2'),
        ),
        migrations.AlterField(
            model_name='tap',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('free', 'Свободно'), ('next', 'След на кран'), ('fresh', 'Свежее/Новое')], default='active', max_length=20, verbose_name='Статус'),
        ),
    ]
