# Generated by Django 4.2.7 on 2025-11-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0005_tap_color_current_tap_color_next1_tap_color_next2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocsinboxStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brewery', models.CharField(max_length=255, verbose_name='Пивоварня')),
                ('beer_name', models.CharField(max_length=255, verbose_name='Название пива')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Локация')),
                ('stock_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Остаток')),
                ('unit', models.CharField(default='шт', max_length=50, verbose_name='Единица измерения')),
                ('docsinbox_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID в DocsInBox')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Остаток DocsInBox',
                'verbose_name_plural': 'Остатки DocsInBox',
                'ordering': ['brewery', 'beer_name'],
                'unique_together': {('brewery', 'beer_name', 'location')},
            },
        ),
    ]
