# Generated by Django 4.2.7 on 2025-11-27 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0006_docsinboxstock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocsinboxStock',
        ),
    ]
