# Generated by Django 4.2.7 on 2025-11-29 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0007_delete_docsinboxstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='TapChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('installed', 'Установлено'), ('removed', 'Убрано'), ('price_changed', 'Изменена цена'), ('queue_shifted', 'Сдвинута очередь'), ('updated', 'Обновлено')], max_length=20, verbose_name='Тип изменения')),
                ('old_brewery', models.CharField(blank=True, max_length=255, verbose_name='Старая пивоварня')),
                ('old_beer_name', models.CharField(blank=True, max_length=255, verbose_name='Старое название')),
                ('old_price_per_liter', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Старая цена')),
                ('new_brewery', models.CharField(blank=True, max_length=255, verbose_name='Новая пивоварня')),
                ('new_beer_name', models.CharField(blank=True, max_length=255, verbose_name='Новое название')),
                ('new_price_per_liter', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Новая цена')),
                ('old_next_beer_1', models.CharField(blank=True, max_length=500, verbose_name='Старое след 1')),
                ('old_next_beer_2', models.CharField(blank=True, max_length=500, verbose_name='Старое след 2')),
                ('new_next_beer_1', models.CharField(blank=True, max_length=500, verbose_name='Новое след 1')),
                ('new_next_beer_2', models.CharField(blank=True, max_length=500, verbose_name='Новое след 2')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('tap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_history', to='parser_app.tap', verbose_name='Кран')),
            ],
            options={
                'verbose_name': 'История изменения крана',
                'verbose_name_plural': 'История изменений кранов',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tap', '-created_at'], name='parser_app__tap_id_a8fe09_idx'), models.Index(fields=['-created_at'], name='parser_app__created_46730e_idx')],
            },
        ),
    ]
