# Generated by Django 4.2.7 on 2025-12-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0008_tapchangehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseditem',
            name='price_unit',
            field=models.CharField(default='unknown', max_length=20, verbose_name='Единица цены'),
        ),
    ]
