# Generated by Django 4.2.7 on 2025-12-17 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0009_parseditem_price_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parseditem',
            name='price_unit',
        ),
    ]
