# Generated by Django 4.2.7 on 2026-02-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0010_remove_parseditem_price_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('google_sheets', 'Google Sheets'), ('zip', 'ZIP Archive')], max_length=20, verbose_name='Тип файла'),
        ),
        migrations.AddIndex(
            model_name='parseditem',
            index=models.Index(fields=['file', 'brewery'], name='parser_app__file_id_8fbe0a_idx'),
        ),
        migrations.AddIndex(
            model_name='parseditem',
            index=models.Index(fields=['file', 'beer_name'], name='parser_app__file_id_3c3257_idx'),
        ),
        migrations.AddIndex(
            model_name='parseditem',
            index=models.Index(fields=['price'], name='parser_app__price_303a8f_idx'),
        ),
        migrations.AddIndex(
            model_name='parseditem',
            index=models.Index(fields=['file', 'is_selected'], name='parser_app__file_id_5e55f1_idx'),
        ),
    ]
