# Generated by Django 4.2.7 on 2026-02-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0011_alter_file_file_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('google_sheets', 'Google Sheets'), ('zip', 'ZIP Archive')], max_length=20, verbose_name='Тип файла'),
        ),
    ]
