# Generated by Django 4.2.7 on 2026-03-01 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parser_app', '0013_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('bartender', 'Бармен'), ('user', 'Пользователь')], default='user', max_length=20, verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.RemoveIndex(
            model_name='parseditem',
            name='parser_app__file_id_8fbe0a_idx',
        ),
        migrations.RemoveIndex(
            model_name='parseditem',
            name='parser_app__file_id_3c3257_idx',
        ),
        migrations.RemoveIndex(
            model_name='parseditem',
            name='parser_app__price_303a8f_idx',
        ),
        migrations.RemoveIndex(
            model_name='parseditem',
            name='parser_app__file_id_5e55f1_idx',
        ),
        migrations.AddField(
            model_name='tap',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Видимость'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
