# Generated by Django 4.2.7 on 2026-05-08 19:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parser_app', '0014_userprofile_and_tap_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParseRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_version', models.CharField(default='legacy', max_length=50, verbose_name='Версия пайплайна')),
                ('status', models.CharField(max_length=20, verbose_name='Статус')),
                ('items_count', models.IntegerField(default=0, verbose_name='Количество позиций')),
                ('warning_count', models.IntegerField(default=0, verbose_name='Количество предупреждений')),
                ('error_count', models.IntegerField(default=0, verbose_name='Количество ошибок')),
                ('parse_kwargs', models.JSONField(blank=True, default=dict, verbose_name='Параметры запуска')),
                ('summary', models.JSONField(blank=True, default=dict, verbose_name='Сводка запуска')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата запуска')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parse_runs', to='parser_app.file', verbose_name='Файл')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parse_runs', to='parser_app.supplier', verbose_name='Поставщик')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parse_runs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запуск парсинга',
                'verbose_name_plural': 'Запуски парсинга',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierColumnMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('exact_file', 'Точный файл'), ('supplier', 'Поставщик'), ('global', 'Глобально')], default='supplier', max_length=20, verbose_name='Область действия')),
                ('source_column', models.CharField(max_length=255, verbose_name='Исходная колонка')),
                ('target_field', models.CharField(max_length=100, verbose_name='Целевое поле')),
                ('file_pattern', models.CharField(blank=True, max_length=255, verbose_name='Паттерн файла')),
                ('confidence', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Уверенность')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='column_mappings', to='parser_app.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Маппинг колонки поставщика',
                'verbose_name_plural': 'Маппинги колонок поставщиков',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['scope', 'source_column'], name='parser_app__scope_5309bc_idx'), models.Index(fields=['target_field'], name='parser_app__target__f64ca9_idx')],
            },
        ),
        migrations.CreateModel(
            name='ParsingFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_column', models.CharField(max_length=255, verbose_name='Исходная колонка')),
                ('suggested_field', models.CharField(max_length=100, verbose_name='Предложенное поле')),
                ('accepted', models.BooleanField(default=True, verbose_name='Принято')),
                ('confidence', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Уверенность')),
                ('note', models.TextField(blank=True, verbose_name='Комментарий')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='Контекст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('parse_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_items', to='parser_app.parserun', verbose_name='Запуск парсинга')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parsing_feedbacks', to='parser_app.supplier', verbose_name='Поставщик')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parsing_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Обратная связь парсинга',
                'verbose_name_plural': 'Обратная связь парсинга',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['accepted', '-created_at'], name='parser_app__accepte_d4327e_idx'), models.Index(fields=['source_column'], name='parser_app__source__9dc81a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='parserun',
            index=models.Index(fields=['pipeline_version', '-created_at'], name='parser_app__pipelin_b29807_idx'),
        ),
        migrations.AddIndex(
            model_name='parserun',
            index=models.Index(fields=['status', '-created_at'], name='parser_app__status_a358e2_idx'),
        ),
    ]
