# Generated by Django 4.2.7 on 2026-05-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0016_tap_availablebeer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablebeer',
            name='abv_text',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Алкоголь (ABV)'),
        ),
        migrations.AddField(
            model_name='availablebeer',
            name='bitterness_ibu',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Горечь (IBU)'),
        ),
        migrations.AddField(
            model_name='availablebeer',
            name='volume_price_text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Объём / цена'),
        ),
        migrations.AddField(
            model_name='tap',
            name='abv_text',
            field=models.CharField(blank=True, default='', help_text='Например «5.2 %»', max_length=32, verbose_name='Алкоголь (ABV)'),
        ),
        migrations.AddField(
            model_name='tap',
            name='bitterness_ibu',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Горечь (IBU)'),
        ),
        migrations.AddField(
            model_name='tap',
            name='volume_price_text',
            field=models.CharField(blank=True, default='', help_text='Краткая строка для экрана, например «30 л · 420 ₽»', max_length=200, verbose_name='Объём / цена'),
        ),
    ]
