# Generated by Django 4.2.7 on 2026-05-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0017_tap_beer_metadata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availablebeer',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Доступное пиво', 'verbose_name_plural': 'Доступное пиво'},
        ),
        migrations.AddField(
            model_name='availablebeer',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок в списке'),
        ),
    ]
